### ISSUE TITLE
PLEASE NERF THE FOURTH SECTOR

### ISSUE THREAD

**Issue by Haznobrain** [Fresh791/asthosus#35]
i can't even begin to describe how insanely HORRIBLE it is.
First attempt i lost to the guardian because its lightning ball is wayyyy too strong
second attempt one pressure pipe got destroyed and my whole defense blew up
PLEASE NERF PRESSURE'S EXPLOSIVITY (and accessorily the damage of t3 tank too)
<img width="647" alt="image" src="https://github.com/Catana791/asthosus/assets/143508779/30c1b0e8-9929-4c8a-bfd6-81126880a557">
second attempt

**Comment by Catana791** [comment]
Most people beat this first try.

**Comment by overdramaticpanromantic** [comment]
I am very sorry to say this, but it's a skill issue. Be faster and get more defenses.

**Comment by Catana791** [comment]
Although a few people have reported the difficulty spike so I did this to mitigate it.
![grafik](https://github.com/Catana791/asthosus/assets/77986574/d0f5eba5-8992-455a-a86c-aacfef34bb8e)
![grafik](https://github.com/Catana791/asthosus/assets/77986574/3501da75-b12a-4704-9525-c63170a3a3d0)

**Comment by Haznobrain** [comment]
> Although a few people have reported the difficulty spike so I did this to mitigate it. ![grafik](https://private-user-images.githubusercontent.com/77986574/313798117-d0f5eba5-8992-455a-a86c-aacfef34bb8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODc3NTEsIm5iZiI6MTcxMDc4NzQ1MSwicGF0aCI6Ii83Nzk4NjU3NC8zMTM3OTgxMTctZDBmNWViYTUtODk5Mi00NTVhLWE4NmMtYWFjZmVmMzRiYjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4NDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMTA0ZGU4NzMzN2UyOTJlMzg5Y2EwMjdkZTkzZDI3Yzc5MWU1MmQwNmYwZjU2ZjM4NzkyNDViNjRhYjAzZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z0UOIfPDg3LeJ1vk7DpB3VH4-3-ts4P2kGjjJjLWFEc) ![grafik](https://private-user-images.githubusercontent.com/77986574/313798141-3501da75-b12a-4704-9525-c63170a3a3d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODc3NTEsIm5iZiI6MTcxMDc4NzQ1MSwicGF0aCI6Ii83Nzk4NjU3NC8zMTM3OTgxNDEtMzUwMWRhNzUtYjEyYS00NzA0LTk1MjUtYzYzMTcwYTNhM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4NDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYjI0ZDI0MWYxOWFjYTRlYWViY2UyOTUxNzQzMzQxZmFhOTVkZjExZGViNTJiMGQyNDA4ZTZkZjU2NTlmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8Jti6PpL9NPpsl7bMLIDwyTpDgVlHBKv86w4lmavB4)

THANKS
also another thing is please don't use artillery bullet type on units it makes them so insanely annoying to defend against until you get point defense weapons T~T
sorry if i'm asking for a bit much i just am trying to explain what i think would be more balanced :<
it's fine if you don't think of it that way and i'm really sorry for bothering you
